### ISSUE TITLE
Decorators to delay and retry a function

### ISSUE THREAD

**Issue by jimmy-lt** [spack971/none#8]
Add decorators to delay or retry a function.

**Comment by harshvvi** [comment]
@spack971  can I work on this. It will be my first PR, so can you tell something more about the task.

**Comment by jimmy-lt** [comment]
Hi @harshvvi,

Thanks for showing interest in the project. This issue is to create 4 decorators that will be in the module `none.callable`.


### Delay

Create two decorators (sync and async) to delay execution of the decorated function.

**Suggested signature**

```python
def delay(secs: typing.Optional[int] = None, max_sleep: int = DEFAULT_MAX_SLEEP):
    ...
```
When ``secs`` is set to ``None``, a random value up to ``max_sleep`` is chosen.


```python
import none

@none.callable.delay(5)
def my_function():
    print("I slept for 5 seconds.")
```

An asynchronous version should be available for asynchronous functions:

```python
import none

@none.callable.adelay(5)
async def my_function():
    print("I asynchronously slept for 5 seconds.")
```

### Retry

Create two decorators (sync and async) to retry the decorated function in case an exception is raised.

**Suggested signature**

```python
def retry(*error: typing.Type[Exception], delay: typing.Optional[int] = None, max_tries: int = DEFAULT_MAX_TRIES, max_sleep: int = DEFAULT_MAX_SLEEP):
    ...
```

When ``delay`` is set to ``None``, a random value up to ``max_sleep`` is chosen.

```python
import none

@none.callable.retry(TimeoutError)
def my_function():
    print("I shall be executed again.")
    raise TimeoutError
```

An asynchronous version should be available for asynchronous functions:

```python
import none

@none.callable.aretry(TimeoutError)
async def my_function():
    print("I shall be executed again.")
    raise TimeoutError
```
